name: Cypress tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Django server
        run: |
          python3 manage.py runserver 0.0.0.0:8080 &
          sleep 10  

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: false 
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 60
          config: baseUrl=http://localhost:8080
