name: Pylint and Hadolint

on: [push]

jobs:
    pylint:
        runs-on: ubuntu-latest
        name: pylint
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python 3.9
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint
                pip install -r requirements.txt
            - name: Analyze code with pylint
              run: |
                pylint --disable=C,R0801 --fail-under=7 $(git ls-files '*.py')
    hadolint:
        runs-on: ubuntu-latest
        name: hadolint
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Lint Dockerfile
              uses: hadolint/hadolint-action@master
              with:
                dockerfile: "Dockerfile"   
            
