name: SAST

on: [push]

jobs:
    tests:
        runs-on: ubuntu-latest
        name: bandit
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python 3.9
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install bandit
                pip install -r requirements.txt
            - name: Run security analysis with bandit
              run: |
                bandit -r . -x ./integration_tests/,./unit_tests/